SELECT P.RDB$PUBLICATION_NAME AS PUBLIKACIJA,
       COUNT(PT.RDB$TABLE_NAME) AS BR_TABELA
FROM RDB$PUBLICATIONS P
LEFT JOIN RDB$PUBLICATION_TABLES PT
ON PT.RDB$PUBLICATION_NAME = P.RDB$PUBLICATION_NAME
GROUP BY P.RDB$PUBLICATION_NAME;
