SELECT
    MON$NEXT_TRANSACTION    AS MASTER_NEXT_TID,
    MON$OLDEST_ACTIVE       AS MASTER_OAT,
    MON$OLDEST_TRANSACTION  AS MASTER_OIT,
    MON$NEXT_TRANSACTION - MON$OLDEST_ACTIVE AS GC_GAP
FROM MON$DATABASE;

